FROM node:20.11.0-bullseye
RUN apt-get update && apt-get -y install curl vim bash nano
WORKDIR /home/node/app
RUN npm install -g pnpm
COPY package.json .
COPY pnpm-lock.yaml .
RUN pnpm install
COPY . .